/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArquivosRouteImport } from './routes/arquivos'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as ConfigRouteImport } from './routes/config'
import { Route as NovaRouteImport } from './routes/nova'
import { Route as ContagemIdRouteImport } from './routes/contagem.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArquivosRoute = ArquivosRouteImport.update({
  id: '/arquivos',
  path: '/arquivos',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigRoute = ConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => rootRouteImport,
} as any)
const NovaRoute = NovaRouteImport.update({
  id: '/nova',
  path: '/nova',
  getParentRoute: () => rootRouteImport,
} as any)
const ContagemIdRoute = ContagemIdRouteImport.update({
  id: '/contagem/$id',
  path: '/contagem/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/arquivos': typeof ArquivosRoute
  '/catalogo': typeof CatalogoRoute
  '/config': typeof ConfigRoute
  '/nova': typeof NovaRoute
  '/contagem/$id': typeof ContagemIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/arquivos': typeof ArquivosRoute
  '/catalogo': typeof CatalogoRoute
  '/config': typeof ConfigRoute
  '/nova': typeof NovaRoute
  '/contagem/$id': typeof ContagemIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/arquivos': typeof ArquivosRoute
  '/catalogo': typeof CatalogoRoute
  '/config': typeof ConfigRoute
  '/nova': typeof NovaRoute
  '/contagem/$id': typeof ContagemIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/arquivos' | '/catalogo' | '/config' | '/nova' | '/contagem/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/arquivos' | '/catalogo' | '/config' | '/nova' | '/contagem/$id'
  id:
    | '__root__'
    | '/'
    | '/arquivos'
    | '/catalogo'
    | '/config'
    | '/nova'
    | '/contagem/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArquivosRoute: typeof ArquivosRoute
  CatalogoRoute: typeof CatalogoRoute
  ConfigRoute: typeof ConfigRoute
  NovaRoute: typeof NovaRoute
  ContagemIdRoute: typeof ContagemIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arquivos': {
      id: '/arquivos'
      path: '/arquivos'
      fullPath: '/arquivos'
      preLoaderRoute: typeof ArquivosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config': {
      id: '/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof ConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nova': {
      id: '/nova'
      path: '/nova'
      fullPath: '/nova'
      preLoaderRoute: typeof NovaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contagem/$id': {
      id: '/contagem/$id'
      path: '/contagem/$id'
      fullPath: '/contagem/$id'
      preLoaderRoute: typeof ContagemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArquivosRoute: ArquivosRoute,
  CatalogoRoute: CatalogoRoute,
  ConfigRoute: ConfigRoute,
  NovaRoute: NovaRoute,
  ContagemIdRoute: ContagemIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
